Remove arial font download.
PsycleResearch/yolov5 pull request #15
Opened 2021-11-15 14:42 UTC by BaptisteAmato

2021-11-15 14:55 UTC, Mindstan requested changes
Cette police ne vient pas par défaut sur toutes les distrib linux car elle est propriété de Microsoft.
Du coup, il faut se la procurer par un autre moyen ou avoir un fallback comme `Nimbus Sans`.

2022-11-21 10:46 UTC, danousna commented
TODO: 
- modifier le docker de base pour bundler les polices utilisées par yolo par défaut (à mettre en dehors du interact storage) :
Arial.ttf, Arial.Unicode.ttf,

2022-11-22 13:13 UTC, Mindstan approved these changes
On peut aussi utiliser une fallback si la police n’est pas présente, comme en CSS

2022-11-22 16:46 UTC, danousna commented
> On peut aussi utiliser une fallback si la police n’est pas présente, comme en CSS

Comment on peut faire ça ? Vu qu'on a potentiellement aucune police de base similaires entre les 3 OS.

2022-11-25 16:12 UTC, closed without merging